AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Hands-on
Resources:
  tradingLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: samAppFunction
      CodeUri: ./src/lambda/agent
      Handler: index.lambda_handler
      Runtime: python3.9
      Architectures: [ x86_64 ]
      Policies:
        - AmazonBedrockFullAccess
        - AmazonS3FullAccess
      Timeout: 30
      MemorySize: 256
      Layers: 
        - !Ref pytzLayer
        - !Ref openpyxlLayer

# ----------------------------- #
# pytz-Layer                  #
# ----------------------------- #
  pytzLayer:
      Type: AWS::Serverless::LayerVersion
      Properties:
        CompatibleRuntimes:
          - python3.9
        ContentUri: ./layer/pandas
        LayerName: "pytzLayer"

# ----------------------------- #
# open-Layer                  #
# ----------------------------- #
  openpyxlLayer:
      Type: AWS::Serverless::LayerVersion
      Properties:
        CompatibleRuntimes:
          - python3.9
        ContentUri: ./layer/openpyxl
        LayerName: "openLayer"