version = 0.1

[default.deploy.parameters]
stack_name = "sam-app-stack"
s3_bucket = "test-shintani-sam"
s3_prefix = ""
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
disable_rollback = false